#ifndef _TZTEST_CONSTANTS_H
#define _TZTEST_CONSTANTS_H

#include "arm32.h"
#include "platform.h"

#define STDOUT 1
#define TZTEST_STATE_SECURE !SCR_NS
#define TZTEST_STATE_NONSECURE SCR_NS

#define SMC_NOOP 0
#define SMC_DISPATCH_MONITOR 1
#define SMC_YIELD 0x32000000
#define SMC_DISPATCH_SECURE_USR 0x32000001
#define SMC_DISPATCH_SECURE_SVC 0x32000002
#define SMC_ALLOCATE_SECURE_MEMORY 0x32000003
#define SMC_EXIT 0x32000004

#define SVC_RETURN_FROM_SECURE_USR 0
#define SVC_DISPATCH_MONITOR 1
#define SVC_DISPATCH_SECURE_USR 2
#define SVC_DISPATCH_SECURE_SVC 3
#define SVC_DISPATCH_NONSECURE_SVC 4
#define SVC_GET_SECURE_STATE 5
#define SVC_EXIT 6

#endif
